### PR TITLE
Update contributing guide

### PR DESCRIPTION
**Pull request by deyemiobaa**
Issue: https://github.com/voscarmv/issue-finder/issues/19

Hey Team. I noticed a few people had trouble setting up the project for the first time so I created an updated contributing guide.

### CODE REVIEW

**Comment by Benmuiruri** [comment]
Good job on this, but I think you should maintain the instruction to run `npm install --save-dev eslint@7.x eslint-config-airbnb@18.x eslint-plugin-import@2.x eslint-plugin-jsx-a11y@6.x eslint-plugin-react@7.x eslint-plugin-react-hooks@4.x @babel/eslint-parser@7.x @babel/core@7.x  @babel/plugin-syntax-jsx@7.x  @babel/preset-react@7.x @babel/preset-react@7.x` because the packages to run the linters are not part of the dependencies. 

Unless I am mistaken, without running that command first `npm run lint` will raise an error.

**Comment by deyemiobaa** [comment]
This isn't necessary. There's already `eslint` in the project dependencies. You can try it out on a branch. I already gave the commands to run/fix the linter checks

**Comment by Benmuiruri** [comment]
Ohh, okay. I had not tried it. Good catch.

**Comment by shadmanhere** [comment]
Welcome back @deyemiobaa and @Benmuiruri.
Thank you for your pull request.

**Review by shadmanhere — COMMENTED** [review]
Hi @deyemiobaa, I really liked the changes you have made to CONTRIBUTING.md.
Just a question, could you clarify what changes you have made in Issues.js?

**Comment by deyemiobaa** [comment]
@shadmanhere
It was the linters, it just rearranged the class-names. No specific change was made to it

**Comment by shadmanhere** [comment]
@deyemiobaa Okay got it 👍

**Review by shadmanhere — APPROVED** [review]

**Pull request merged**
